apiVersion: v1
kind: Service
metadata:
  name: a2f-grpc-server-headless
  labels:
    app: a2f-grpc-server
spec:
  clusterIP: None
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  selector:
    app: a2f-grpc-server
