apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a2f-model-data
  labels:
    app: a2f-grpc-server
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
