apiVersion: v1
kind: Service
metadata:
  name: tarot
spec:
  type: NodePort
  ports:
  - port: 4007
    targetPort: 4007
    nodePort: 30007  # localhost에서 이 포트로 접근
    protocol: TCP
    name: websocket
