apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarot
spec:
  template:
    spec:
      containers:
      - name: tarot
        command:
          - "uvicorn"
          - "app:app"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "4007"
        # SSL 옵션 제거 (로컬 테스트용 HTTP만 사용)
